### ISSUE TITLE
Private repos?

### ISSUE THREAD

**Issue by zeke** [zeit/hazel#11]
Does hazel on work on public repos? Supporting private repos would required a GitHub token, which apparently is not currently required or used by hazel.

**Comment by leo** [comment]
We're most likely never going to support private repositories since the assets are being downloaded directly from GitHub by the client (to save bandwidth).

In turn, the client would have to authenticate with GitHub.

**Comment by dominiklessel** [comment]
@leo I've got a first working version of hazel which supports private repos over here: https://github.com/mifitto/hazel I a pull request something you're interested in?

**Comment by leo** [comment]
@dominiklessel Yesss! 😍

**Comment by dominiklessel** [comment]
Great 😄 I will test it internally first and try to find out if its working as expected!

**Comment by zeke** [comment]
nice

**Comment by leo** [comment]
Just landed in https://github.com/zeit/hazel/pull/23
