### ISSUE TITLE
Windows 10 not detected properly

### ISSUE THREAD

**Issue by Stanzilla** [zeit/hazel#19]
UserAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3218.0 Safari/537.36

gives No download available for your platform!

**Comment by leo** [comment]
Chrome 62 is the latest version, so you must be on a beta/canary version... 😊

**Comment by Stanzilla** [comment]
@leo so? Why would Chrome version be relevant for OS detection?

**Comment by leo** [comment]
@Stanzilla Anything can change in beta versions. It works fine on Chrome 62 on Windows 10.
