### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by dbuezas** [zeit/hazel#2]
Great stuff! Any plans for adding authentication?

**Comment by leo** [comment]
Why? For private repos?

**Comment by dbuezas** [comment]
yes, for private repos

**Comment by leo** [comment]
This doesn't make sense, because Hazel is proxying the assets from GitHub Releases. So if your repository is private, the user can't access the releases.

**Comment by dbuezas** [comment]
my use case is an internal app not for the open public, if you have any recommendation for that it would be great
