### ISSUE TITLE
Fails after missing token

### ISSUE THREAD

**Issue by nparsons08** [zeit/hazel#24]
What's up with the token requirement? It's not clear at all... and it exits out of the deployment if you don't provide one.

**Comment by leo** [comment]
cc @dominiklessel any ideas?

**Comment by nparsons08** [comment]
For what it's worth, I forked the project and removed the requirement. It deployed without any issues.

**Comment by leo** [comment]
@nparsons08 Can you share the command you used to deploy it?

**Comment by nparsons08** [comment]
Sure thing. I used my forked version:

```
now -e NODE_ENV="production" nparsons08/hazel
```

**Comment by nparsons08** [comment]
@leo I'm using this for a (now) private repo. What token is that and how do I set it after the fact?

**Comment by dominiklessel** [comment]
I've never deployed something with now and totally missed the fact that NOW_URL is always set over there. I've removed the check and addressed the issue in PR #25

Just to clarify: Hazel needs the TOKEN (https://github.com/settings/tokens) to access the private repo. You can create a new token here: https://github.com/settings/tokens/new
