### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by sindresorhus** [zeit/hazel#27]
Would be nice to have some tests to prevent future regressions.

Example: https://github.com/sindresorhus/gh-latest-repos/blob/master/test.js

**Comment by leo** [comment]
@dominiklessel You said you would be up for tackling this, still interested? 😊

**Comment by dominiklessel** [comment]
@leo I will give it a shot tomorrow.

**Comment by leo** [comment]
@dominiklessel Wonderful, thank you!

**Comment by leo** [comment]
Landed! Thanks to @timneutkens
