### ISSUE TITLE
The `/download` route should return the DMG and not ZIP on macOS

### ISSUE THREAD

**Issue by sindresorhus** [zeit/hazel#41]
The `/download` route is useful for providing a direct link to the latest release, but currently, it returns the ZIP file, which is only meant for updates, and not the DMG file, which is meant for end-users.

**Comment by leo** [comment]
Interesting take on this @sindresorhus! 😊 

I think I agree with it, since not providing an installer often leads to our customers opening the application from the "Downloads" directory.

But so far, we simply used .zip because Safari unzips by default, so you directly get what you want into your "Downloads" folder: The application - no further setup required...

**Comment by sindresorhus** [comment]
> But so far, we simply used .zip because Safari unzips by default, so you directly get what you want into your "Downloads" folder: The application - no further setup required...

Users just running the app from `Downloads` leads to other problems too, see https://github.com/sindresorhus/electron-util#enforcemacosapplocation

**Comment by leo** [comment]
@sindresorhus I didn't mean that it's a good idea to run it in the Downloads directory, but rather good for users to directly get what they want and then drag it to any place from there.

But yes, anyway, I agree with you - we should be serving the `.dmg` on `/download` and the `.zip` only for the updates.

**Comment by jlongster** [comment]
I'd love this too. Any update on it? I need this so if nobody else is going it I'll probably try to do it myself.

**Comment by HaNdTriX** [comment]
Any progress on this?

**Comment by ZeroDragon** [comment]
On chrome instead of opening it. You get a warning saying that the zip file might be malicious ...

**Comment by itsnwa** [comment]
There are currently issues with electron-builder(?) on macOS Catalina that makes apps unable to open when it is extracted from zip (works fine with dmg). This change would fix that problem ✨

I tried pulling down the latest with the changes from #69 but getting an error accessing the `download/dmg` route: `No download available for your platform`. (the dmg does exist in the release)

**Comment by julienma** [comment]
Just to say that I'm using PR #53 in production since a few months now, and it works fine for me.

**Comment by rwwagner90** [comment]
@leo is there any chance we could work with @julienma and get this fixed up? I tried his PR, but it doesn't seem to work for me, unless there is some additional setup I missed.

**Comment by beninada** [comment]
Would be great to have the option of downloading pkg as well.

**Comment by itsnwa** [comment]
Did something change in the GitHub API? I haven't updated the server or app, but the dmg route no longer works.
