### ISSUE TITLE
Support for Linux

### ISSUE THREAD

**Issue by harisvsulaiman** [zeit/hazel#5]
Linux support would be awesome to have, since updating electron apps in Linux is not fun, especially if you have to work in a low connectivity area.

**Comment by leo** [comment]
Electron currently [doesn't support](https://electron.atom.io/docs/api/auto-updater/#linux) linux updates.

**Comment by Aarbel** [comment]
any updates about that ?

**Comment by Aarbel** [comment]
@leo
