### ISSUE TITLE
How to use hazel with github Team's private repository ?

### ISSUE THREAD

**Issue by Aarbel** [zeit/hazel#55]
I've got this error in the `Now project's logs`: 

```
(node:1) UnhandledPromiseRejectionWarning: Error: GitHub API responded with 404 for url https://api.github.com/repos/MY_TEAM/MY_ELECTRON_REPO/releases?per_page=100
```

Hazel doesn't find (or doesn't have access to) the private team's repository. Do you know a way to make it work ? Thanks a lot !

**Comment by f3d0r** [comment]
Using the `TOKEN` environment variable as specified [here](https://github.com/zeit/hazel#options) is probably what you're looking for!

**Comment by Aarbel** [comment]
i'll check this week ;)

**Comment by euroclydon37** [comment]
I can't get this to work. The server is returning a download url of 
```
"https://api.github.com/repos/<user>/<repo>/releases?access_token=<my_token>/download/darwin"
```

It seems like the `NOW_URL` isn't being set.

**Comment by Aarbel** [comment]
Solved running this :
```
now -e ACCOUNT="YourTeamOrPrivateUserName" -e REPOSITORY="YourRepoName" -e TOKEN="YOURGITHUBTOKEN" -e URL="https://api.github.com/repos/<YourTeamOrPrivateUserName>/<YourRepoName>/releases?access_token=<YOURGITHUBTOKEN>"
```

![image](https://user-images.githubusercontent.com/25119847/55993112-91b2f480-5cae-11e9-8546-94def1eefb93.png)

**Comment by RafalWilinski** [comment]
It still does not fully work. I admit that downloading from landing page seems fine. However, when autoupdater calls url `https://hazel.rwilinski.now.sh/update/darwin/0.0.9` it receives following JSON.
```
{"name":"0.0.11","notes":"Bulk deleting","pub_date":"2019-09-12T11:49:21Z","url":"https://api.github.com/repos/RafalWilinski/dynamodb-gui/releases?access_token=8f093dd105e36e08bc9f71f44d018d6ae3922dc6/download/darwin"}

**Comment by jsfuentes** [comment]
So I actually got it to work by setting the URL to the update server url, not the github API. The update server works with private repos by serving as a proxy to github releases(see https://github.com/zeit/hazel/pull/23):

now -e ACCOUNT=<YourTeamOrPrivateUserName> -e REPOSITORY=<YourRepoName> -e TOKEN=<YOURGITHUBTOKEN> -e URL="https://<THE DOMAIN OF YOUR UPDATE SERVER>.now.sh

**Comment by Sectaur** [comment]
Update for clarification. The command has changed:

notes: 
REPOSITORY = the name of the repository that contains the app that you are updating via Github Releases.
YOURGITHUBTOKEN = remember to give the token appropriate permissions when you generate.



`vercel -e ACCOUNT=<YourGithubTeamOrGithubAccountUserName> -e REPOSITORY=<YourRepoName> -e TOKEN=<YOURGITHUBTOKEN> -e URL="https://<THE DOMAIN OF YOUR UPDATE SERVER>`
