### ISSUE TITLE
What is the url of latest .dmg or .exe ?

### ISSUE THREAD

**Issue by Aarbel** [zeit/hazel#61]
![image](https://user-images.githubusercontent.com/25119847/55998504-cc248d80-5cbe-11e9-928e-78aed7a93760.png)

I want to put a direct download of the lasted version of my electron app on my website (both for mac and windows).
## What should be the right url to the hazel update server to directly download .dmg and .exe but not .zip ?

Thanks for your help !

**Comment by KASOGIT** [comment]
Ping

**Comment by elmasry** [comment]
@doesdev fixed that in his fork https://github.com/doesdev/hazel/

Ref: https://github.com/zeit/hazel/pull/56

**Comment by Aarbel** [comment]
@elmasry is that merged with hazel ?

**Comment by elmasry** [comment]
@Aarbel nope

**Comment by Aarbel** [comment]
What's the brake to merge it ?

**Comment by Aarbel** [comment]
@AndyBitz could you add this feature ? ❤️

**Comment by AndyBitz** [comment]
@Aarbel On [hyper.is](https://hyper.is/#installation) we use `/download/mac` and `/download/win`. Would that work for you?

**Comment by AndyBitz** [comment]
Oh, I see that it only downloads the exe for windows, but not the dmg for mac. I'll look into it

**Comment by AndyBitz** [comment]
@Aarbel this PR provides a way to download `dmg` files: https://github.com/zeit/hazel/pull/69

**Comment by Aarbel** [comment]
> @Aarbel On [hyper.is](https://hyper.is/#installation) we use `/download/mac` and `/download/win`. Would that work for you?

`/download/mac` downloads a .zip (i want a .dmg),  `/download/win` downloads an .exe (so no problem about .exe)

**Comment by Aarbel** [comment]
Thanks a lot @AndyBitz
